<?php
/**
 * @author Alan Sherry http://drupal.org/user/941916
 * @file
 * D3 API for creating visualizations with d3, and d3 libraries.
 *
 * Sponsored by http://www.freeflowdigital.com
 */

/**
 * Implements hook_theme().
 */
function d3_theme() {

  foreach (libraries_info() as $path => $library) {
    // call this function to get all fields - i.e. library path
    $library = libraries_load($path);
    // if a template was specified in the .info file or hook_libraries_info
    if (isset($library['template'])) {
      // change d3.[library name] to d3_[library name] for a theme key
      $theme_key = str_replace('.', '_', $library['machine name']);
      $themes[$theme_key] = array(
        'template' => $library['template'],
        'path' => $library['library path'],
      );
    }
  }

  $themes['d3'] = array(
    'variables' => array(),
    'template' => 'd3',
  );

  $themes['d3_graphapi'] = array(
    'variables' => array(
      'graph' => NULL,
      'config' => NULL,
    ),
  );

  return $themes;
}

/**
 * Implements hook_preprocess_[hook].
 */
function d3_preprocess_d3(&$variables) {

  // let drupal_attributes render this
  $variables['classes_array'][] = $variables['type'];
  $variables['attributes_array']['id'] = array($variables['vis_id']);

  $library = isset($variables['library']) ? $variables['library'] : FALSE;

  // let's look for a template file in the library definition
  if (isset($library['template'])) {
    $variables['theme_hook_suggestion'] = isset($library['library name']) ? $library['library name'] : str_replace('.', '_', $library['machine name']);
  }
}

/**
 * Implements hook_libraries_paths().
 */
function d3_libraries_info_file_paths() {

  // get all library directories
  $libraries = libraries_get_libraries();

  $paths = array();
  // output an array of paths to check for
  foreach ($libraries as $id => $path) {
    $paths[] = $path;
  }

  // load the directory where the d3 example libraries are
  $example_path = drupal_get_path('module', 'd3') . '/libraries/';

  // add these to the search directories for libraries
  foreach (d3_default_libraries() as $example) {
    $paths[] = $example_path . $example;
  }

  return $paths;
}

/**
 * Implements hook_requirements().
 */
function d3_requirements($phase) {
  $requirements = array();
  // Run only for reporting.
  if ($phase != 'runtime') {
    return $requirements;
  }

  // If this is run during install we'll need to use get_t instead of 
  // just t
  $t = get_t();
  // If the library directory exists.
  if ($path = libraries_get_path('d3')) {
    // Check for a d3 javascript file, ignoring the version and if it is
    // minified or not.
    if ($files = file_scan_directory($path, '/d3.*.js/')) {
      $requirements['d3'] = array(
        'title' => $t('D3'),
        'value' => '',
        'severity' => REQUIREMENT_OK,
      );

      // Return a list of all the files that exist.
      foreach ($files as $file) {
        $requirements['d3']['value'] .= $file->filename . ' ';
      }

      // Report has passed.
      $requirements['d3']['value'] .= $t('found under !path', array('!path' => $path));
    }
    else {
      // If there are no javascript files, then there was a problem
      // installing the library.
      $requirements['d3'] = array(
        'title' => $t('D3'),
        'value' => isset($lib['error message']) 
          ? $t($lib['error message']) 
          : t('The d3 library has not been installed properly. Check your folder 
            !path and ensure your d3.[version].js file is located inside that 
            folder, and not in a subfolder.', array('!path' => $path)),
        'severity' => REQUIREMENT_ERROR,
      );
    }

    return $requirements;
  }
  else {
    // If there is no library at all, chances are they have not downloaded
    // and tried installing D3 yet.
    $requirements['d3'] = array(
      'title' => $t('D3'),
      'value' => isset($lib['error message'])
        ? $t($lib['error message'])
        : t('D3 library was not found. !download the library and place all javascript 
          files in a folder entitled "d3" located in your default libraries folder. 
          E.g. If you download version 3 minified, it would be located 
          in path/to/libraries/d3/d3.v3.min.js.', array('!download' => l(t('Download'), 'https://github.com/mbostock/d3'))
      ),
      'severity' => REQUIREMENT_ERROR,
    );

    return $requirements;
  }
}

/**
 * Implements hook_libraries_info_alter().
 */
function d3_libraries_info_alter(&$libraries) {

  $path = drupal_get_path('module', 'd3') . '/libraries/';

  foreach (d3_default_libraries() as $library_name) {
    $libraries[$library_name]['library path'] = $path . $library_name;
  }
}

/**
 * Implements hook_libraries_info().
 */
function d3_libraries_info() {

  $libraries = array();

  // drupal ext adds behaviors and d3 global object
  $libraries['d3.drupal'] = array(
    'name' => 'D3 Drupal ext',
    'vendor url' => 'http://drupal.org/sandbox/asherry/1477334',
    'files' => array(
      'js' => array(
        'd3.js',
      ),
    ),
    'path' => 'js',
    'library path' => drupal_get_path('module', 'd3'),
    'version' => '1',
  );

  $libraries['d3'] = array(
    'name' => 'D3',
    'vendor url' => 'http://d3js.org/',
    'download url' => 'https://github.com/mbostock/d3',
    'files' => array(
      'js' => array(
        'd3.v3.min.js',
      ),
    ),
    'version' => '3',
    'dependencies' => array('d3.drupal'),
  );

  return $libraries;
}

/**
 * Helper callback to return all sample libraries located inside this module.
 */
function d3_default_libraries() {
  return array(
    'd3.columnchart',
    'd3.extend',
    'd3.forcedirected',
    'd3.module_dependencies',
    'd3.linegraph',
    'd3.tooltip',
    'd3.barchart',
    'd3.piechart',
  );
}

/**
 * D3's main API callback.
 *
 * @param array $vis
 *   The chart data
 * @return string
 *   Rendered chart html
 */
function d3_draw($vis) {

  // type is required for correct processing
  $type = isset($vis['type']) ? strtolower($vis['type']) : NULL;

  if (!$type) {
    drupal_set_message(t('No chart type specified'));
    return '';
  }

  // form library name - convention is going to be d3.[library]
  $library_name = 'd3.' . $type;

  // check for library instance / definition
  if ($library = libraries_detect($library_name)) {
    $vis['library'] = libraries_load($library_name);
    $vis['library']['library name'] = str_replace('.', '_', $library_name);
    // Enforce lowercase change.
    $vis['type'] = $type;
    // store as vis_id because key ['id'] will get overridden
    $vis['vis_id'] = $vis['id'];

    // now add to the behaviors to execute on page load
    $js = array(
      'd3' => array(
        'inventory' => array($vis['id'] => $vis),
      ),
    );
    drupal_add_js($js, 'setting');

    // renders the html - .tpl.php if specified or default d3.tpl.php
    return theme('d3', $vis);

  }
  else {
    drupal_set_message(t('Invalid chart type %type and/or library %library_name is not installed', array(
      '%type' => $type,
      '%library_name' => $library_name
    )));
    return '';
  }
}

/**
 * Provides an array of d3 libraries.
 *
 * D3 libraries are going to have a prefix of d3., see README.txt
 * for information on creating a custom d3 library.
 */
function d3_get_libraries() {

  static $d3_libraries;

  if ($d3_libraries) {
    return $d3_libraries;
  }
  // Returns all libraries in the default folders.
  $libraries = libraries_info();

  foreach ($libraries as $library) {
    $library_name = $library['machine name'];
    // Filter out any other non-d3 library. All d3 libraries should have
    // the prefix "d3.".
    if (strpos($library_name, 'd3.') === FALSE) {
      continue;
    }
    // Do not list these default extension libraries.
    if (in_array($library_name, array('d3.extend', 'd3.tooltip', 'd3.drupal'))) {
      continue;
    }

    $d3_libraries[$library_name] = $library;
    $d3_libraries[$library_name]['js callback'] = str_replace('d3.', '', $library_name);
  }

  return $d3_libraries;
}
/**
 * Implements hook_graphapi_formats().
 */
function d3_graphapi_formats() {
  return array(
    'd3' => t('D3'),
  );
}

/**
 * Implements hook_graphapi_settings_form().
 */
function d3_graphapi_settings_form($values) {

  $engine = 'd3';
  $form[$engine] = array(
    '#type' => 'fieldset',
    '#title' => 'D3 settings',
  );

  $options = array();
  foreach (d3_get_libraries() as $name => $library) {
    $options[$library['js callback']] = $library['name'];
  }
  $form[$engine]['library'] = array(
    '#title' => 'Default library',
    '#description' => t('Use this d3 library as the default to render graphapi visualizations'),
    '#type' => 'select',
    '#options' => $options,
    '#default_value' => variable_get('d3_graphapi_default_library', 'forcedirected'),
  );

  $form[$engine]['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Save',
    '#submit' => array('d3_graphapi_settings_form_submit'),
  );

  return $form;

}

/**
 * Submit handler for the graphapi settings form.
 *
 * @see d3_graphapi_settings_form()
 */
function d3_graphapi_settings_form_submit(&$form, &$form_state) {
  variable_set('d3_graphapi_default_library', $form_state['values']['library']);
}


/**
 * Converts $graph data array two arrays for links and nodes.
 *
 * @param array $graph
 *   Associative array of nodes with link information and data.
 *
 * @return array
 *   Links and nodes.
 */
function _d3_graphapi_format_graph_data($graph) {
  $data = array();
  $indices = array();
  $index = 0;

  foreach ($graph as $id => $node) {
    $indices[$id] = $index;
    $index++;
  }

  // add in edges
  foreach ($graph as $id => $node) {
    $index = $indices[$id];
    $data['nodes'][$index] = array(
      'name' => $node['data']['title'],
      'group' => isset($node['data']['group']) ? $node['data']['group'] : 1,
      'data' => $node['data'],
    );
    if (count($node['edges']) > 0) {
      foreach ($node['edges'] as $edge => $edge_data) {
        $value = isset($edge_data['data']['value']) ? (int) $edge_data['data']['value'] : NULL;

        $data['links'][] = array(
          'data' => isset($edge_data['data']) ? $edge_data['data'] : array(),
          'source' => $index,
          'target' => $indices[$edge],
          'value' => $value, //TODO hard coded should be dynamic
        );
      }
    }
  }

  return $data;
}

/**
 * Displays the visualization for graphapi's selected library.
 */
function theme_d3_graphapi($vars) {
  $library = variable_get('d3_graphapi_default_library', 'forcedirected');

  $graph = _d3_graphapi_format_graph_data($vars['graph']);
  $chart = array(
    'id' => 'visualization',
    'type' => $library,
    'links' => $graph['links'],
    'nodes' => $graph['nodes'],
    'config' => $vars['config'],
  );
  return d3_draw($chart);
}

/**
 * Implements hook_graphapi_default_settings().
 *
 * We reuse the default settings from thejit_forcedirected_default_settings.
 *
 * @see thejit_forcedirected_default_settings()
 * @see views_object::option_definition()
 */
function d3_graphapi_default_settings() {
  return array(
    'd3' => array(
      'library' => array('default' => 'd3.forcedirected'),
    ),
  );
}
