<?php

/**
 * Implements hook_views_api()
 */
function d3_views_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'd3_views') . '/views',
  );
}

/**
 * Implements hook_theme().
 */
function d3_views_theme() {

  return array(
    'views_ui_style_d3_plugin_table' => array(
      'render element' => 'form',
    ),  
  );

}

/**
 * Theme the form for the table style plugin
 */
function theme_views_ui_style_d3_plugin_table($variables) {
  $form = $variables['form'];

  $output = drupal_render($form['library']);

  $header = array(
    t('Field'),
    t('Data type'),
  );
  $rows = array();
  foreach (element_children($form['columns']) as $id) {
    $row = array();
    $row[] = drupal_render($form['columns'][$id]['name']);
    $row[] = drupal_render($form['columns'][$id]['type']);
    
    $rows[] = $row;
  }

  $output .= theme('table', array('header' => $header, 'rows' => $rows));
  $output .= drupal_render_children($form);
  return $output;
}
